version: '3'
services:
  collect-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test123! # If planned to deploy, create more secure password and store it securely
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - collectnet

  collect-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:collect=Server=collect-sql,1433;Database=210370;User=sa;Password=Test123!;ConnectRetryCount=0;Trusted_Connection=false;
    ports:
      - 5010:5010
    networks:
      - collectnet
    links:
      - collect-sql
    depends_on:
      - collect-sql

networks:
  collectnet:
    driver: bridge
