version: '3'
services:
  collect-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test123! # If planned to deploy, create more secure password and store it securely
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - evetnet

  collect-api:
    restart: unless-stopped
    build:
      context: .
    environment:
		# For the MVP sake, provided credentials are safe to store on github
		# They're not going to be deployed anywhere
      - ConnectionStrings:collect=Server=collect-sql,1433;Database=IB130149;User=sa;Password=Test123!;ConnectRetryCount=0
    ports:
      - 5000:80
    networks:
      - evetnet      
    links:
      - collect-sql
    depends_on:
      - collect-sql

networks:
  evetnet:
    driver: bridge 
